### ISSUE TITLE
Is there an option to just backup the structure without the data?

### ISSUE THREAD

**Issue by wink-** [Delta-Solutions/mysqltools#1]
Is there an option for just creating the sql file and comparing the structure of the database without the data?

**Comment by dietercoopman** [comment]
Hey, i think you need the mysql:compare command.  Or do you want a structure dump without the data ? I you want that I will add it soon ( this week ), is a nice feature.  Could be 

```
mysqltools mysql:backup --nodata 
```

I'm also open for contributions, so if you want to add it yourself, you can do so.

**Comment by dietercoopman** [comment]
Hey,  this feature has been added in version 1.0.4 , thx for the suggestion
